### ISSUE TITLE
Big std::strings in nvarchar(max)s via ODBC fails with HY104

### ISSUE THREAD

**Issue by Superlokkus** [SOCI/soci#287]
Hi, soci throws odbc_soci_error when the std::string I use is very long (4096 worked but failed at 29906).
The ODBC error code is HY104, so I guess soci does not handle big strings right (to be fair due typical ODBC driver implementation limitations), or I overlooked the way to handle them with soci. The according column is defined as nvarchar(max), the server is an MS SQLServer 2008RC2 and the ODBC-Driver uses the SQL Server Native Client 11.0 on Windows 7 Prof.

**Comment by vadz** [comment]
If the driver doesn't handle strings of this size, I don't think SOCI should do anything about it. Try using BLOBs instead of the strings instead perhaps?

**Comment by Superlokkus** [comment]
@vadz AFAIK is supposed to work see https://msdn.microsoft.com/de-de/library/ms130896.aspx

**Comment by mloskot** [comment]
The sole reference of [SQLBindParameter parameter ColumnSize](https://msdn.microsoft.com/en-us/library/ms710963.aspx) does not say it all.

AFAIU, in case a large object exceeds certain range (see below), then the `ColumnSize` is not set with actual size of the object, but with special constant. See [Binding Parameters for SQL Character Types](https://msdn.microsoft.com/en-us/library/ms131462.aspx):
>  If the SQL data type passed in is a character type, ColumnSize is the size in characters (not bytes). If the length of the data string in bytes is greater than 8000, ColumnSize should be set to SQL_SS_LENGTH_UNLIMITED, indicating that there is no limit to the size of the SQL type.
>
> For instance, if the SQL data type is SQL_WVARCHAR, ColumnSize should not be greater than 4000. If the actual data length is greater than 4000, then ColumnSize should be set to SQL_SS_LENGTH_UNLIMITED so that nvarchar(max) will be used by driver.

I may be misunderstanding, so it would be good if someone could confirm that.

Currently, `SQL_SS_LENGTH_UNLIMITED` case is not handled.

**Comment by vadz** [comment]
I could try testing this, but what exactly is the test case here? I.e. does it happen when writing a long value to the database or when reading it from it?

**Comment by Superlokkus** [comment]
Writing

**Comment by mloskot** [comment]
Yeah, it's always helpful if a bug report is accompanied with (pseudo)code sample or, preferably, [CATCH](https://github.com/philsquared/Catch/blob/master/docs/tutorial.md)-based test case.

**Comment by Superlokkus** [comment]
I understand here is my preliminary example, closely based on the setup I encountered it (MS SQLServer 2008RC2 and the ODBC-Driver uses the SQL Server Native Client 11.0 on Windows 7 Prof.)

I will try to deliver a catch based test, but I don't visit my workplace until next week, so please wait until next week for a better example, i.e. reproduced with a different setup.

```C++
soci::register_factory_odbc();
soci::connection_parameters main_session_parameters(soci::odbc, ODBC_CONNECTION_STRING);
main_session_parameters.set_option("odbc_option_driver_complete", "0");
soci::session current_session(main_session_parameters);

string log = {/*Long string bigger > 8000 */}

current_session << "UPDATE files SET ... uploader_log = :log where ...", ... soci::use(log, "log"); // Will throw soci::odbc_soci_error as mentioned above
```
Table: 
```SQL
CREATE TABLE files (
file_id uniqueidentifier NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID() ROWGUIDCOL,

...
uploader_log nvarchar(max) NULL,

CONSTRAINT unique_file UNIQUE(directory_id,file_name)
);
```

**Comment by vadz** [comment]
I don't see the error but this could be due to ODBC driver difference. I do see the problem with the string being just truncated to 8000 characters silently which is arguable even worse. The PR #328 fixes it for me, please test if it helps with your problem too or if it's a different one.

**Comment by mloskot** [comment]
@Superlokkus  :+1:

**Comment by vadz** [comment]
Should be fixed by c025cc86968914bd4bd0523dee11cdd9db991aba

**Comment by Superlokkus** [comment]
Since AFAIK your fix commit c025cc86968914bd4bd0523dee11cdd9db991aba is included in today's master: Is not fixed by your commit. MS SQL still reports 

```
[2015-Sep-30 10:27:56.736424, 0x00001a48] 4: Cought execption when tried to register file: Error binding input parameter #2: [Microsoft][SQL Server Native Client 11.0]Invalid precision value (SQL state HY104) while executing "UPDATE files SET read_time = :time, partially_uploaded = 1,uploader_log = :log where file_name = :name AND directory_id = (select directory_id from directories where full_path = :path)" with :name="16689.VS", :path="\\192.168.205.40\Data_Share_RHE\RHE_OPERATIONS\01_Fertigung\05_Messtechnik\02_Elektrisch\Novell\TESTDATA\SSR1000", :time=2015-09-30 10:27:56, :log="Error: Invalid data format!
```

I really try to get a test case working, but I'm still a C++ novice.

**Comment by vadz** [comment]
Sorry, I'm really not sure how/why did this happen, but it turns out that c025cc8 has never been merged into master. I've just (finally) done it now, sorry for the confusion.

**Comment by snikulov** [comment]
@vadz it was fixed in #383. Please revert your last commit on master. Because it breaks the tests (ref appveiour results)

**Comment by mloskot** [comment]
Was AppVeyor not broken before?

**Comment by snikulov** [comment]
@mloskot Not in odbc tests - thanks for history

**Comment by mloskot** [comment]
@snikulov OK, I might have not paid enough attention

**Comment by vadz** [comment]
Oops, sorry about this, I didn't realize it had been applied and then replaced by 0723512f39a21cd78ebee017a84fb3f617b3e4ba, reverted now.
