### ISSUE TITLE
std::strings in nvarchar(max) is still a problem

### ISSUE THREAD

**Issue by picant** [SOCI/soci#383]
Reading string trough ODBC version 11 still does not work for nvarchar(max) columns (yes I'm aware of issue #287). ODBC version 10 works just fine.

Environment:
windows 8.1
msvc 2013
soci version 4 (from 8-Sep-2015)

Database setup:
use history
create table test ( data nvarchar (MAX) not null );
insert into test (data) values ('Aaa')

Test source code:

```
#define SOCI_USE_BOOST
#include <soci.h>            // SOCI components
#include <soci-config.h>
#include <odbc/soci-odbc.h>
#include <afxcontrolbars.h>
using namespace soci;

//const char* connectionString = "DRIVER={SQL Server};Server=192.168.11.54\\SPSQL;Uid=sa;Pwd=Master10"; //<<<<this works
const char* connectionString = "DRIVER={ODBC Driver 11 for SQL Server};Server=192.168.11.54\\SPSQL;Uid=sa;Pwd=Master10"; //<<<<THIS DOESN'T WORK

    session sql;
    sql.open(connection_parameters("odbc", connectionString));

    sql << "use history";

    rowset<row> rs = sql.prepare << "select * from test";
    for (auto it = rs.begin(); it != rs.end(); ++it)
    {
        std::string data;
        data = it->get<std::string>("data"); //this returns empty string if ODBC 11 is used
    }
```

**Comment by vadz** [comment]
Does our [existing test case](https://github.com/SOCI/soci/commit/c025cc86968914bd4bd0523dee11cdd9db991aba#diff-917ce54c9a333ec67257b8d86dd712baR23) fail as well? If not, could you please try to update the test case to show the failure in it?

**Comment by picant** [comment]
I can't build your tests as I run into all kind of build problems if I use -DSOCI_TESTS=ON :(

Looking at your test code I can suggest to replace 'fixed_text nvarchar(4000)' with 'fixed_text nvarchar(max)' in your test test-odbc-mssql.cpp and check if the test still runs fine if you use ODBC driver version 11. Or even better try to replace 'nvarchar(num)' and 'varchar(num)' with 'nvarchar(max)' everywhere in your odbc tests.

**Comment by vadz** [comment]
Strange, what problems are those? You may want to open another issue for them...

**Comment by picant** [comment]
Done. Created issue #384 about the build problems.

**Comment by toeb** [comment]
Hi,  I currently added a really bad hack to soci to quickly allow me to write the long strings.  I found the solution by readin this post and its links: http://stackoverflow.com/questions/14860330/sqlbindparameter-with-sql-varbinarymax-gives-invalid-precision-value  .

I'm sorry that I don't have the time for a patch/pull request currently but thought you might want to know the changes I made (which are very ugly but seem to work.):

these changes are not tested in soci nor anywhere else than my application for that matter.  

both are in `standard-use-type.cpp`

```cpp
void odbc_standard_use_type_backend::pre_use(indicator const *ind)
{
    // first deal with data
    SQLSMALLINT sqlType(0);
    SQLSMALLINT cType(0);
    SQLLEN size(0);

    void* const sqlData = prepare_for_bind(size, sqlType, cType);

    SQLRETURN rc;
    if(sqlType == SQL_LONGVARCHAR && size > 8000)
    {
        
        rc = SQLBindParameter(
        statement_.hstmt_, //StatementHandle
        static_cast<SQLUSMALLINT>(position_), //ParameterNumber
        SQL_PARAM_INPUT,//InputOutputType
        SQL_C_CHAR, //cType, //ValueType
        SQL_VARCHAR, //sqlType, //ParameterType
        0, //ColumnSize
        0,//DecimalDigits
        sqlData, //ParameterValuePtr
        size,//BufferLength
        NULL //StrLen_or_IndPtr
        );

    }
    else
    {
        
        rc = SQLBindParameter(
        statement_.hstmt_, //StatementHandle
        static_cast<SQLUSMALLINT>(position_), //ParameterNumber
        SQL_PARAM_INPUT,//InputOutputType
        cType, //ValueType
        sqlType, //ParameterType
        size, //ColumnSize
        0,//DecimalDigits
        sqlData, //ParameterValuePtr
        0,//BufferLength
        &indHolder_//StrLen_or_IndPtr
        );

    }



    if (is_odbc_error(rc))
    {
        std::ostringstream ss;
        ss << "binding input parameter #" << position_;
        throw odbc_soci_error(SQL_HANDLE_STMT, statement_.hstmt_, ss.str());
    }

    // then handle indicators
    if (ind != NULL && *ind == i_null)
    {
        indHolder_ = SQL_NULL_DATA; // null
    }
}

```

In prepare_for_bind replace the x_stdstring case with: 
```cpp
 case x_stdstring:
    {
        std::string const& s = exchange_type_cast<x_stdstring>(data_);
        sqlType = SQL_VARCHAR;
        cType = SQL_C_CHAR;
        size = s.size();
        buf_ = new char[size+1];
        memcpy(buf_, s.c_str(), size);
        buf_[size++] = '\0';
        indHolder_ = SQL_NTS;

        // Strings of greater length are silently truncated at 8000 limit by MS
        // SQL unless SQL_SS_LENGTH_UNLIMITED (which is defined as 0, but not
        // available in all headers) is used.
        if (size > 8000)
        {
          sqlType = SQL_LONGVARCHAR;        
        }
    }
    break;

```

**Comment by toeb** [comment]
I also had a problem when reading long strings into a `soci::row`.  I also chose a very quick and dirty route to solve it currently.

The problem is in `odbc_standard_into_type_backend::define_by_pos` which allocates a zero buffer if a column is unbounded `nvarchar(max)`  I chose to quickly just allocate 100 MB, but that is not a solution I can keep up for long.  The zero value is obtained when using the odbc column describe method for the unbounded column.

May this is a separate issue but I think it is very related to this one.


```cpp
case x_stdstring:
        odbcType_ = SQL_C_CHAR;
        // Patch: set to min between column size and 100MB (used ot be 32769)
        // Column size for text data type can be too large for buffer allocation
        size = static_cast<SQLUINTEGER>(statement_.column_size(position_));
        // ^^ size is zero for columns which are larger than 8000 (nvarchar(max))
        // the following is probably the stupidest solution to the problem:
        size = size > odbc_max_buffer_length ? odbc_max_buffer_length : size;
        if(size==0)
        {
          // allocate 100MB to read an arbitrary large string....  (not good, but at least it works for now)
            size = odbc_max_buffer_length;
        }
        else
        {
            size++;
        }
        buf_ = new char[size];
        data = buf_;
        break;
```

**Comment by mloskot** [comment]
@toeb Thanks for sharing your patch. I'm hoping to try it out after the new year.

**Comment by snikulov** [comment]
Should be fixed with pull https://github.com/SOCI/soci/pull/489

**Comment by snikulov** [comment]
Landed on master https://github.com/SOCI/soci/commit/0723512f39a21cd78ebee017a84fb3f617b3e4ba

**Comment by vadz** [comment]
This issue still exists when using old (but unfortunately still widespread, because they seem to be included either in Windows itself or in Office, and so are de facto always available everywhere) MS SQL Server ODBC drivers.

I.e. the "MS SQL long string" test from `tests/odbc/test-odbc-mssql.cpp` fails with "SQL Server" ODBC driver v6.01 and v10.100 but succeeds when using "SQL Server Native Client 11.0" driver v2011.110.

I think we need to use `SQL_LONGVARCHAR` to make it work with the old drivers, as originally proposed by @toeb.
